name: talya_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  rxdart: ^0.28.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.1.1
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.19.0
  get_it: ^7.1.3
  tuple: ^2.0.2
  video_player: ^2.2.19
  flutter_credit_card: ^4.0.1
  webview_flutter: ^4.8.0
  lottie: ^3.1.2
  clipboard: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
    - assets/failure-animation.json
    - assets/success-animation.json


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
